sonar.projectKey=DPU_mesh_dxs-traceinfo-flink-streaming-wl
sonar.sourceEncoding=UTF-8
sonar.sources=flink-app/src/main/java
sonar.tests=flink-app/src/test/java
sonar.java.binaries=flink-app/target/classes
sonar.java.test.binaries=flink-app/target/test-classes
sonar.coverage.exclusions=**/*.java
sonar.java.libraries=flink-app/target/
