{
  "fields": [
    {
      "javaAnnotation": "javax.validation.constraints.NotBlank",
      "name": "uuid",
      "type": "string"
    },
    {
      "javaAnnotation": "javax.validation.constraints.NotBlank",
      "name": "eventType",
      "type": "string"
    },
    {
      "name": "eventTimestamp",
      "type": {
        "logicalType": "timestamp-millis",
        "type": "long"
      }
    },
    {
      "javaAnnotation": "javax.validation.constraints.PositiveOrZero",
      "name": "dossierId",
      "type": "long"
    },
    {
      "javaAnnotation": "javax.validation.constraints.Pattern(regexp = \"^[A-Za-z0-9_]+$\")",
      "name": "applicationCode",
      "type": "string"
    },
    {
      "default": null,
      "javaAnnotation": "javax.annotation.Nullable\n  @javax.validation.constraints.Pattern(regexp = \"^(PAPER|PEC|BRANCH_INDIVIDUALS|DIGITAL)$\")",
      "name": "selectedProcessType",
      "type": [
        "null",
        "string"
      ]
    },
    {
      "javaAnnotation": "javax.validation.constraints.Pattern(regexp = \"^(Y|N)?$\")",
      "name": "reprint",
      "type": "string"
    },
    {
      "javaAnnotation": "javax.validation.constraints.Pattern(regexp = \"^[A-Za-z0-9_]+$\")",
      "name": "exeApp",
      "type": "string"
    },
    {
      "javaAnnotation": "javax.validation.constraints.Pattern(regexp = \"^[A-Za-z0-9_.:-]+$\")",
      "name": "correlationKey",
      "type": "string"
    },
    {
      "javaAnnotation": "javax.validation.constraints.NotBlank",
      "name": "author",
      "type": "string"
    },
    {
      "javaAnnotation": "javax.validation.constraints.Pattern(regexp = \"^(CREATED|DRAFT|DRAFT_PEC|PROCESSING|RETRY_ON_PROCESS|PEC_PROCESSING|TO_BE_ACCEPTED|TO_BE_CLOSED|EXPIRED|CANCELLED|CONCLUDED|CLOSED)$\")",
      "name": "status",
      "type": "string"
    },
    {
      "default": null,
      "javaAnnotation": "javax.annotation.Nullable",
      "name": "subStatus",
      "type": [
        "null",
        "string"
      ]
    },
    {
      "javaAnnotation": "javax.validation.constraints.Pattern(regexp = \"^[0-9]{5}$\")",
      "name": "branch",
      "type": "string"
    },
    {
      "default": null,
      "javaAnnotation": "javax.annotation.Nullable\n  @javax.validation.constraints.Pattern(regexp = \"^(FORCED_BY_VERTICAL|SELECTED_BY_USER|)$\")",
      "name": "paperReason",
      "type": [
        "null",
        "string"
      ]
    },
    {
      "default": null,
      "javaAnnotation": "javax.annotation.Nullable",
      "name": "practiceId",
      "type": [
        "null",
        "string"
      ]
    },
    {
      "default": null,
      "javaAnnotation": "javax.annotation.Nullable\n  @javax.validation.constraints.Pattern(regexp = \"^(B2C|C2B)$\")",
      "name": "pecFlow",
      "type": [
        "null",
        "string"
      ]
    },
    {
      "javaAnnotation": "javax.validation.constraints.Pattern(regexp = \"^[0-9]{5}$\")",
      "name": "bankCode",
      "type": "string"
    },
    {
      "default": null,
      "javaAnnotation": "javax.annotation.Nullable",
      "name": "relatedDossier",
      "type": [
        "null",
        "string"
      ]
    },
    {
      "default": null,
      "javaAnnotation": "javax.annotation.Nullable\n  @javax.validation.constraints.Pattern(regexp = \"^[0-9]+$\")",
      "name": "masterDossierId",
      "type": [
        "null",
        "string"
      ]
    },
    {
      "default": null,
      "javaAnnotation": "javax.annotation.Nullable",
      "name": "motivation",
      "type": [
        "null",
        "string"
      ]
    },
    {
      "javaAnnotation": "javax.validation.constraints.Pattern(regexp = \"^(ENTERPRISE|UCX)$\")",
      "name": "dossierType",
      "type": "string"
    },
    {
      "default": null,
      "javaAnnotation": "javax.annotation.Nullable\n  @javax.validation.constraints.Pattern(regexp = \"^[0-9]{5}$\")",
      "name": "referenceBranchPec",
      "type": [
        "null",
        "string"
      ]
    },
    {
      "default": null,
      "javaAnnotation": "javax.annotation.Nullable",
      "name": "legalEntity",
      "type": [
        "null",
        "string"
      ]
    },
    {
      "default": null,
      "javaAnnotation": "javax.annotation.Nullable\n  @javax.validation.constraints.Pattern(regexp = \"^(PF|PG)$\")",
      "name": "flowType",
      "type": [
        "null",
        "string"
      ]
    },
    {
      "name": "creationDate",
      "type": {
        "logicalType": "timestamp-millis",
        "type": "long"
      }
    },
    {
      "name": "endDate",
      "type": {
        "logicalType": "timestamp-millis",
        "type": "long"
      }
    },
    {
      "javaAnnotation": "javax.validation.Valid",
      "name": "customers",
      "type": {
        "items": {
          "fields": [
            {
              "javaAnnotation": "javax.validation.constraints.Pattern(regexp = \"^[0-9]+$\")",
              "name": "ndg",
              "type": "string"
            },
            {
              "javaAnnotation": "javax.validation.constraints.Pattern(regexp = \"^[A-Z][A-Z0-9_]*$\")",
              "name": "type",
              "type": "string"
            },
            {
              "javaAnnotation": "javax.validation.constraints.NotBlank",
              "name": "selectedChannels",
              "type": "string"
            }
          ],
          "name": "Customer",
          "type": "record"
        },
        "type": "array"
      }
    },
    {
      "javaAnnotation": "javax.validation.Valid",
      "name": "documentGroups",
      "type": {
        "items": {
          "fields": [
            {
              "javaAnnotation": "javax.validation.constraints.PositiveOrZero",
              "name": "id",
              "type": "long"
            },
            {
              "default": null,
              "javaAnnotation": "javax.annotation.Nullable",
              "name": "digilayerId",
              "type": [
                "null",
                "string"
              ]
            },
            {
              "default": null,
              "javaAnnotation": "javax.annotation.Nullable",
              "name": "envelopeId",
              "type": [
                "null",
                "string"
              ]
            },
            {
              "javaAnnotation": "javax.validation.constraints.Pattern(regexp = \"^(CREATED|DRAFT|DISABLED|LOCKED|READY|PROCESSING_PARTIALLY_SIGNED|TO_BE_ARCHIVED|TO_BE_CONFIRMED|PROCESSING|UPLOADED|TO_BE_PRINTED|PRINTED|CANCELLED|CANCELLED_ARCHIVED|CANCELLED_CREATED|CANCELLED_DRAFT|CANCELLED_LOCKED|CANCELLED_SENT|ARCHIVED|AUTOMATIC_ARCHIVED|CLOSED|EXPIRED|ERROR_SIGNAL|TO_BE_UPLOADED|TO_BE_ACKNOWLEDGED|ARCHIVED_CANCELED|SIGNED|HIDDEN)$\")",
              "name": "status",
              "type": "string"
            },
            {
              "name": "creationDate",
              "type": {
                "logicalType": "timestamp-millis",
                "type": "long"
              }
            },
            {
              "name": "endDate",
              "type": {
                "logicalType": "timestamp-millis",
                "type": "long"
              }
            },
            {
              "javaAnnotation": "javax.validation.Valid",
              "name": "signers",
              "type": {
                "items": {
                  "fields": [
                    {
                      "javaAnnotation": "javax.validation.constraints.PositiveOrZero",
                      "name": "id",
                      "type": "long"
                    },
                    {
                      "javaAnnotation": "javax.validation.constraints.Pattern(regexp = \"^[0-9]+$\")",
                      "name": "ndg",
                      "type": "string"
                    },
                    {
                      "default": null,
                      "javaAnnotation": "javax.annotation.Nullable\n  @javax.validation.constraints.Pattern(regexp = \"^[A-Z][A-Z0-9_]*$\")",
                      "name": "mfaMethod",
                      "type": [
                        "null",
                        "string"
                      ]
                    },
                    {
                      "default": null,
                      "javaAnnotation": "javax.annotation.Nullable\n  @javax.validation.constraints.Pattern(regexp = \"^.+$\")",
                      "name": "authenticationId",
                      "type": [
                        "null",
                        "string"
                      ]
                    },
                    {
                      "default": null,
                      "javaAnnotation": "javax.annotation.Nullable\n  @javax.validation.constraints.Pattern(regexp = \"^[0-9]+$\")",
                      "name": "signerReb",
                      "type": [
                        "null",
                        "string"
                      ]
                    },
                    {
                      "default": null,
                      "javaAnnotation": "javax.annotation.Nullable\n  @javax.validation.constraints.Pattern(regexp = \"^[0-9]+$\")",
                      "name": "signatureChannel",
                      "type": [
                        "null",
                        "string"
                      ]
                    },
                    {
                      "name": "signatureDate",
                      "type": {
                        "logicalType": "timestamp-millis",
                        "type": "long"
                      }
                    }
                  ],
                  "name": "Signer",
                  "type": "record"
                },
                "type": "array"
              }
            },
            {
              "javaAnnotation": "javax.validation.Valid",
              "name": "documents",
              "type": {
                "items": {
                  "fields": [
                    {
                      "javaAnnotation": "javax.validation.constraints.PositiveOrZero",
                      "name": "id",
                      "type": "long"
                    },
                    {
                      "default": null,
                      "javaAnnotation": "javax.validation.constraints.Pattern(regexp = \"^[A-Za-z][A-Za-z0-9_]*$\")",
                      "name": "code",
                      "type": [
                        "null",
                        "string"
                      ]
                    },
                    {
                      "default": null,
                      "javaAnnotation": "javax.validation.constraints.Pattern(regexp = \"^(CREATED|DOC_GENERATED|PRINTED|ARCHIVED|ARCHIVE_SKIPPED|IN_ARCHIVING|TO_BE_ARCHIVED|BO_APPROVAL|RM_APPROVAL|CONTROLS_FAILED|CANCELLED|CONFIRMED|REJECTED|UPLOADED)$\")",
                      "name": "status",
                      "type": [
                        "null",
                        "string"
                      ]
                    },
                    {
                      "default": null,
                      "javaAnnotation": "javax.validation.constraints.Pattern(regexp = \"^[A-Z][A-Z0-9_]*$\")",
                      "name": "categoryCode",
                      "type": [
                        "null",
                        "string"
                      ]
                    },
                    {
                      "default": null,
                      "javaAnnotation": "javax.validation.constraints.NotBlank",
                      "name": "productName",
                      "type": [
                        "null",
                        "string"
                      ]
                    },
                    {
                      "default": null,
                      "javaAnnotation": "javax.validation.constraints.NotBlank",
                      "name": "processCode",
                      "type": [
                        "null",
                        "string"
                      ]
                    },
                    {
                      "default": null,
                      "javaAnnotation": "javax.annotation.Nullable\n  @javax.validation.constraints.Pattern(regexp = \"^(ARCHIVE|PAPER|PEC|SIGN|UPLOAD)?$\")",
                      "name": "processType",
                      "type": [
                        "null",
                        "string"
                      ]
                    },
                    {
                      "default": null,
                      "javaAnnotation": "javax.annotation.Nullable\n  @javax.validation.constraints.PositiveOrZero",
                      "name": "size",
                      "type": [
                        "null",
                        "long"
                      ]
                    },
                    {
                      "default": null,
                      "javaAnnotation": "javax.annotation.Nullable\n  @javax.validation.constraints.Pattern(regexp = \"^[^|]+\\\\|\\\\d{4}-\\\\d{2}-\\\\d{2}T\\\\d{2}:\\\\d{2}:\\\\d{2}(?:\\\\.\\\\d{1,9})?(?:Z|[+-]\\\\d{2}:\\\\d{2})\\\\|[^|]+\\\\|[^|]+$\")",
                      "name": "controlsOutcomePec",
                      "type": [
                        "null",
                        "string"
                      ]
                    },
                    {
                      "default": null,
                      "javaAnnotation": "javax.annotation.Nullable\n  @javax.validation.constraints.Pattern(regexp = \"^[A-Z][A-Z0-9_]*$\")",
                      "name": "signatureTypePec",
                      "type": [
                        "null",
                        "string"
                      ]
                    },
                    {
                      "default": null,
                      "javaAnnotation": "javax.annotation.Nullable",
                      "name": "certificateAuthorityPec",
                      "type": [
                        "null",
                        "string"
                      ]
                    },
                    {
                      "default": null,
                      "javaAnnotation": "javax.annotation.Nullable\n  @javax.validation.constraints.Pattern(regexp = \"^\\\\d{4}-\\\\d{2}-\\\\d{2}T\\\\d{2}:\\\\d{2}:\\\\d{2}(?:\\\\.\\\\d{1,9})?(?:Z|[+-]\\\\d{2}:\\\\d{2})$\")",
                      "name": "signaturePointTimestampPec",
                      "type": [
                        "null",
                        "string"
                      ]
                    },
                    {
                      "default": null,
                      "javaAnnotation": "javax.annotation.Nullable\n  @javax.validation.constraints.Pattern(regexp = \"^(Y|N)?$\")",
                      "name": "accessibility",
                      "type": [
                        "null",
                        "string"
                      ]
                    },
                    {
                      "default": null,
                      "javaAnnotation": "javax.annotation.Nullable\n  @javax.validation.constraints.Pattern(regexp = \"^\\\\./[A-Za-z0-9._/-]*$\")",
                      "name": "archiveLink",
                      "type": [
                        "null",
                        "string"
                      ]
                    },
                    {
                      "default": null,
                      "javaAnnotation": "javax.annotation.Nullable\n  @javax.validation.constraints.PositiveOrZero",
                      "name": "numberOfPages",
                      "type": [
                        "null",
                        "long"
                      ]
                    },
                    {
                      "default": null,
                      "javaAnnotation": "javax.annotation.Nullable\n  @javax.validation.constraints.Pattern(regexp = \"^[0-9]+$\")",
                      "name": "accountNumber",
                      "type": [
                        "null",
                        "string"
                      ]
                    },
                    {
                      "default": null,
                      "javaAnnotation": "javax.annotation.Nullable",
                      "name": "documentDescription",
                      "type": [
                        "null",
                        "string"
                      ]
                    },
                    {
                      "default": null,
                      "javaAnnotation": "javax.annotation.Nullable\n  @javax.validation.constraints.Pattern(regexp = \"^[A-Z][A-Z0-9_]*$\")",
                      "name": "signatureType",
                      "type": [
                        "null",
                        "string"
                      ]
                    },
                    {
                      "default": null,
                      "javaAnnotation": "javax.annotation.Nullable\n  @javax.validation.constraints.Pattern(regexp = \"^(Y|N)?$\")",
                      "name": "digitalization",
                      "type": [
                        "null",
                        "string"
                      ]
                    },
                    {
                      "default": null,
                      "javaAnnotation": "javax.annotation.Nullable",
                      "name": "datamatrix",
                      "type": [
                        "null",
                        "string"
                      ]
                    },
                    {
                      "default": null,
                      "javaAnnotation": "javax.annotation.Nullable",
                      "name": "signatureBoxOrder",
                      "type": [
                        "null",
                        "string"
                      ]
                    },
                    {
                      "name": "creationDate",
                      "type": {
                        "logicalType": "timestamp-millis",
                        "type": "long"
                      }
                    },
                    {
                      "name": "endDate",
                      "type": {
                        "logicalType": "timestamp-millis",
                        "type": "long"
                      }
                    },
                    {
                      "name": "signatureDate",
                      "type": {
                        "logicalType": "timestamp-millis",
                        "type": "long"
                      }
                    }
                  ],
                  "name": "Document",
                  "type": "record"
                },
                "type": "array"
              }
            }
          ],
          "name": "DocumentGroup",
          "type": "record"
        },
        "type": "array"
      }
    }
  ],
  "name": "DossierTraceinfoEvent",
  "namespace": "eu.unicredit.dxs",
  "type": "record"
}