kafka:
  bootstrapServers: ckfprdlsr01.internal.unicreditgroup.eu:9092,ckfprdlsr02.internal.unicreditgroup.eu:9092
  topic: DXSUIWWDPUPRD
  consumerGroupId: DXS01DXSUIWWDPUPRD
  ldapGroup: JUIDXSDPU_CKFPR
  partitions: 12

schemaRegistry:
  url: http://ckfprdlsr01.internal.unicreditgroup.eu:8081

flink:
  parallelism: 12
  checkpointIntervalMs: 60000
  checkpointTimeoutMs: 120000
  minPauseBetweenCheckpointsMs: 20000

catalog:
  catalogLocation: 'gs://dxs_traceinfo_ew8_production/0/dxs-traceinfo-dremio-storage-area'