projectId: "prj-dpu-prd-dataplatform-001"

kafka:
  bootstrapServers: ckfprdlbrk01.internal.unicreditgroup.eu:9093,ckfprdlbrk02.internal.unicreditgroup.eu:9093,ckfprdlbrk03.internal.unicreditgroup.eu:9093,ckfprdlbrk04.internal.unicreditgroup.eu:9093,ckfprdlbrk05.internal.unicreditgroup.eu:9093,ckfprdlbrk06.internal.unicreditgroup.eu:9093,ckfprdlbrk07.internal.unicreditgroup.eu:9093,ckfprdlbrk08.internal.unicreditgroup.eu:9093,ckfprdlbrk09.internal.unicreditgroup.eu:9093,ckfprdlbrk10.internal.unicreditgroup.eu:9093
  topic: DXSUIWWDPUPRD
  consumerGroupId: DXS01DXSUIWWDPUPRD
  ldapGroup: JUIDXSDPU_CKFPR
  partitions: 12

schemaRegistry:
  url: http://ckfprdlsr01.internal.unicreditgroup.eu:8081

flink:
  baseParallelism: 12
  checkpointInterval: "PT2H"
  checkpointIntervalMs: 60000
  checkpointTimeoutMs: 120000
  minPauseBetweenCheckpointsMs: 20000

catalog:
  catalogLocation: 'gs://dxs_traceinfo_ew8_production/0/dxs-traceinfo-dremio-storage-area'