projectId: "prj-dpu-dev-dataplatform-001"

kafka:
  bootstrapServers: ckfdevlsr01.internal.unicreditgroup.eu:9092
  topic: DXSUIWWDPUSIT
  consumerGroupId: DXS01DXSUIWWDPUSIT
  ldapGroup: JUIDXSDPU_CKFDR
  partitions: 3

schemaRegistry:
  url: http://ckfdevlsr01.internal.unicreditgroup.eu:8081

flink:
  baseParallelism: 3
  checkpointInterval: "PT2H"

catalog:
  catalogLocation: 'gs://dxs_traceinfo_ew8_development/0/dxs-traceinfo-dremio-storage-area'