/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package eu.unicredit.dxs;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class Customer extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 4214957393459831781L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Customer\",\"namespace\":\"eu.unicredit.dxs\",\"fields\":[{\"name\":\"ndg\",\"type\":\"string\"},{\"name\":\"type\",\"type\":\"string\"},{\"name\":\"selectedChannels\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Customer> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Customer> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<Customer> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<Customer> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<Customer> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this Customer to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a Customer from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a Customer instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static Customer fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.CharSequence ndg;
  private java.lang.CharSequence type;
  private java.lang.CharSequence selectedChannels;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Customer() {}

  /**
   * All-args constructor.
   * @param ndg The new value for ndg
   * @param type The new value for type
   * @param selectedChannels The new value for selectedChannels
   */
  public Customer(java.lang.CharSequence ndg, java.lang.CharSequence type, java.lang.CharSequence selectedChannels) {
    this.ndg = ndg;
    this.type = type;
    this.selectedChannels = selectedChannels;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return ndg;
    case 1: return type;
    case 2: return selectedChannels;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: ndg = (java.lang.CharSequence)value$; break;
    case 1: type = (java.lang.CharSequence)value$; break;
    case 2: selectedChannels = (java.lang.CharSequence)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'ndg' field.
   * @return The value of the 'ndg' field.
   */
  public java.lang.CharSequence getNdg() {
    return ndg;
  }


  /**
   * Sets the value of the 'ndg' field.
   * @param value the value to set.
   */
  public void setNdg(java.lang.CharSequence value) {
    this.ndg = value;
  }

  /**
   * Gets the value of the 'type' field.
   * @return The value of the 'type' field.
   */
  public java.lang.CharSequence getType() {
    return type;
  }


  /**
   * Sets the value of the 'type' field.
   * @param value the value to set.
   */
  public void setType(java.lang.CharSequence value) {
    this.type = value;
  }

  /**
   * Gets the value of the 'selectedChannels' field.
   * @return The value of the 'selectedChannels' field.
   */
  public java.lang.CharSequence getSelectedChannels() {
    return selectedChannels;
  }


  /**
   * Sets the value of the 'selectedChannels' field.
   * @param value the value to set.
   */
  public void setSelectedChannels(java.lang.CharSequence value) {
    this.selectedChannels = value;
  }

  /**
   * Creates a new Customer RecordBuilder.
   * @return A new Customer RecordBuilder
   */
  public static eu.unicredit.dxs.Customer.Builder newBuilder() {
    return new eu.unicredit.dxs.Customer.Builder();
  }

  /**
   * Creates a new Customer RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Customer RecordBuilder
   */
  public static eu.unicredit.dxs.Customer.Builder newBuilder(eu.unicredit.dxs.Customer.Builder other) {
    if (other == null) {
      return new eu.unicredit.dxs.Customer.Builder();
    } else {
      return new eu.unicredit.dxs.Customer.Builder(other);
    }
  }

  /**
   * Creates a new Customer RecordBuilder by copying an existing Customer instance.
   * @param other The existing instance to copy.
   * @return A new Customer RecordBuilder
   */
  public static eu.unicredit.dxs.Customer.Builder newBuilder(eu.unicredit.dxs.Customer other) {
    if (other == null) {
      return new eu.unicredit.dxs.Customer.Builder();
    } else {
      return new eu.unicredit.dxs.Customer.Builder(other);
    }
  }

  /**
   * RecordBuilder for Customer instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Customer>
    implements org.apache.avro.data.RecordBuilder<Customer> {

    private java.lang.CharSequence ndg;
    private java.lang.CharSequence type;
    private java.lang.CharSequence selectedChannels;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(eu.unicredit.dxs.Customer.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.ndg)) {
        this.ndg = data().deepCopy(fields()[0].schema(), other.ndg);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.type)) {
        this.type = data().deepCopy(fields()[1].schema(), other.type);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.selectedChannels)) {
        this.selectedChannels = data().deepCopy(fields()[2].schema(), other.selectedChannels);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
    }

    /**
     * Creates a Builder by copying an existing Customer instance
     * @param other The existing instance to copy.
     */
    private Builder(eu.unicredit.dxs.Customer other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.ndg)) {
        this.ndg = data().deepCopy(fields()[0].schema(), other.ndg);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.type)) {
        this.type = data().deepCopy(fields()[1].schema(), other.type);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.selectedChannels)) {
        this.selectedChannels = data().deepCopy(fields()[2].schema(), other.selectedChannels);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'ndg' field.
      * @return The value.
      */
    public java.lang.CharSequence getNdg() {
      return ndg;
    }


    /**
      * Sets the value of the 'ndg' field.
      * @param value The value of 'ndg'.
      * @return This builder.
      */
    public eu.unicredit.dxs.Customer.Builder setNdg(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.ndg = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'ndg' field has been set.
      * @return True if the 'ndg' field has been set, false otherwise.
      */
    public boolean hasNdg() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'ndg' field.
      * @return This builder.
      */
    public eu.unicredit.dxs.Customer.Builder clearNdg() {
      ndg = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'type' field.
      * @return The value.
      */
    public java.lang.CharSequence getType() {
      return type;
    }


    /**
      * Sets the value of the 'type' field.
      * @param value The value of 'type'.
      * @return This builder.
      */
    public eu.unicredit.dxs.Customer.Builder setType(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.type = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'type' field has been set.
      * @return True if the 'type' field has been set, false otherwise.
      */
    public boolean hasType() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'type' field.
      * @return This builder.
      */
    public eu.unicredit.dxs.Customer.Builder clearType() {
      type = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'selectedChannels' field.
      * @return The value.
      */
    public java.lang.CharSequence getSelectedChannels() {
      return selectedChannels;
    }


    /**
      * Sets the value of the 'selectedChannels' field.
      * @param value The value of 'selectedChannels'.
      * @return This builder.
      */
    public eu.unicredit.dxs.Customer.Builder setSelectedChannels(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.selectedChannels = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'selectedChannels' field has been set.
      * @return True if the 'selectedChannels' field has been set, false otherwise.
      */
    public boolean hasSelectedChannels() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'selectedChannels' field.
      * @return This builder.
      */
    public eu.unicredit.dxs.Customer.Builder clearSelectedChannels() {
      selectedChannels = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Customer build() {
      try {
        Customer record = new Customer();
        record.ndg = fieldSetFlags()[0] ? this.ndg : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.type = fieldSetFlags()[1] ? this.type : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.selectedChannels = fieldSetFlags()[2] ? this.selectedChannels : (java.lang.CharSequence) defaultValue(fields()[2]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Customer>
    WRITER$ = (org.apache.avro.io.DatumWriter<Customer>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Customer>
    READER$ = (org.apache.avro.io.DatumReader<Customer>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.ndg);

    out.writeString(this.type);

    out.writeString(this.selectedChannels);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.ndg = in.readString(this.ndg instanceof Utf8 ? (Utf8)this.ndg : null);

      this.type = in.readString(this.type instanceof Utf8 ? (Utf8)this.type : null);

      this.selectedChannels = in.readString(this.selectedChannels instanceof Utf8 ? (Utf8)this.selectedChannels : null);

    } else {
      for (int i = 0; i < 3; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.ndg = in.readString(this.ndg instanceof Utf8 ? (Utf8)this.ndg : null);
          break;

        case 1:
          this.type = in.readString(this.type instanceof Utf8 ? (Utf8)this.type : null);
          break;

        case 2:
          this.selectedChannels = in.readString(this.selectedChannels instanceof Utf8 ? (Utf8)this.selectedChannels : null);
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










