/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package eu.unicredit.dxs;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class Document extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -6288383119758121582L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Document\",\"namespace\":\"eu.unicredit.dxs\",\"fields\":[{\"name\":\"id\",\"type\":\"long\"},{\"name\":\"code\",\"type\":\"string\"},{\"name\":\"status\",\"type\":\"string\"},{\"name\":\"categoryCode\",\"type\":\"string\"},{\"name\":\"productName\",\"type\":\"string\"},{\"name\":\"processCode\",\"type\":\"string\"},{\"name\":\"processType\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"size\",\"type\":[\"null\",\"long\"],\"default\":null},{\"name\":\"controlsOutcomePec\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"signatureTypePec\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"certificateAuthorityPec\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"signaturePointTimestampPec\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"accessibility\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"archiveLink\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"numberOfPages\",\"type\":[\"null\",\"long\"],\"default\":null},{\"name\":\"accountNumber\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"documentDescription\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"signatureType\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"digitalization\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"datamatrix\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"creationDate\",\"type\":{\"type\":\"long\",\"logicalType\":\"timestamp-millis\"}},{\"name\":\"endDate\",\"type\":{\"type\":\"long\",\"logicalType\":\"timestamp-millis\"}},{\"name\":\"signatureDate\",\"type\":{\"type\":\"long\",\"logicalType\":\"timestamp-millis\"}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();
  static {
    MODEL$.addLogicalTypeConversion(new org.apache.avro.data.TimeConversions.TimestampMillisConversion());
  }

  private static final BinaryMessageEncoder<Document> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Document> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<Document> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<Document> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<Document> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this Document to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a Document from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a Document instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static Document fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private long id;
  private java.lang.CharSequence code;
  private java.lang.CharSequence status;
  private java.lang.CharSequence categoryCode;
  private java.lang.CharSequence productName;
  private java.lang.CharSequence processCode;
  private java.lang.CharSequence processType;
  private java.lang.Long size;
  private java.lang.CharSequence controlsOutcomePec;
  private java.lang.CharSequence signatureTypePec;
  private java.lang.CharSequence certificateAuthorityPec;
  private java.lang.CharSequence signaturePointTimestampPec;
  private java.lang.CharSequence accessibility;
  private java.lang.CharSequence archiveLink;
  private java.lang.Long numberOfPages;
  private java.lang.CharSequence accountNumber;
  private java.lang.CharSequence documentDescription;
  private java.lang.CharSequence signatureType;
  private java.lang.CharSequence digitalization;
  private java.lang.CharSequence datamatrix;
  private java.time.Instant creationDate;
  private java.time.Instant endDate;
  private java.time.Instant signatureDate;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Document() {}

  /**
   * All-args constructor.
   * @param id The new value for id
   * @param code The new value for code
   * @param status The new value for status
   * @param categoryCode The new value for categoryCode
   * @param productName The new value for productName
   * @param processCode The new value for processCode
   * @param processType The new value for processType
   * @param size The new value for size
   * @param controlsOutcomePec The new value for controlsOutcomePec
   * @param signatureTypePec The new value for signatureTypePec
   * @param certificateAuthorityPec The new value for certificateAuthorityPec
   * @param signaturePointTimestampPec The new value for signaturePointTimestampPec
   * @param accessibility The new value for accessibility
   * @param archiveLink The new value for archiveLink
   * @param numberOfPages The new value for numberOfPages
   * @param accountNumber The new value for accountNumber
   * @param documentDescription The new value for documentDescription
   * @param signatureType The new value for signatureType
   * @param digitalization The new value for digitalization
   * @param datamatrix The new value for datamatrix
   * @param creationDate The new value for creationDate
   * @param endDate The new value for endDate
   * @param signatureDate The new value for signatureDate
   */
  public Document(java.lang.Long id, java.lang.CharSequence code, java.lang.CharSequence status, java.lang.CharSequence categoryCode, java.lang.CharSequence productName, java.lang.CharSequence processCode, java.lang.CharSequence processType, java.lang.Long size, java.lang.CharSequence controlsOutcomePec, java.lang.CharSequence signatureTypePec, java.lang.CharSequence certificateAuthorityPec, java.lang.CharSequence signaturePointTimestampPec, java.lang.CharSequence accessibility, java.lang.CharSequence archiveLink, java.lang.Long numberOfPages, java.lang.CharSequence accountNumber, java.lang.CharSequence documentDescription, java.lang.CharSequence signatureType, java.lang.CharSequence digitalization, java.lang.CharSequence datamatrix, java.time.Instant creationDate, java.time.Instant endDate, java.time.Instant signatureDate) {
    this.id = id;
    this.code = code;
    this.status = status;
    this.categoryCode = categoryCode;
    this.productName = productName;
    this.processCode = processCode;
    this.processType = processType;
    this.size = size;
    this.controlsOutcomePec = controlsOutcomePec;
    this.signatureTypePec = signatureTypePec;
    this.certificateAuthorityPec = certificateAuthorityPec;
    this.signaturePointTimestampPec = signaturePointTimestampPec;
    this.accessibility = accessibility;
    this.archiveLink = archiveLink;
    this.numberOfPages = numberOfPages;
    this.accountNumber = accountNumber;
    this.documentDescription = documentDescription;
    this.signatureType = signatureType;
    this.digitalization = digitalization;
    this.datamatrix = datamatrix;
    this.creationDate = creationDate.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
    this.endDate = endDate.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
    this.signatureDate = signatureDate.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return code;
    case 2: return status;
    case 3: return categoryCode;
    case 4: return productName;
    case 5: return processCode;
    case 6: return processType;
    case 7: return size;
    case 8: return controlsOutcomePec;
    case 9: return signatureTypePec;
    case 10: return certificateAuthorityPec;
    case 11: return signaturePointTimestampPec;
    case 12: return accessibility;
    case 13: return archiveLink;
    case 14: return numberOfPages;
    case 15: return accountNumber;
    case 16: return documentDescription;
    case 17: return signatureType;
    case 18: return digitalization;
    case 19: return datamatrix;
    case 20: return creationDate;
    case 21: return endDate;
    case 22: return signatureDate;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  private static final org.apache.avro.Conversion<?>[] conversions =
      new org.apache.avro.Conversion<?>[] {
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      new org.apache.avro.data.TimeConversions.TimestampMillisConversion(),
      new org.apache.avro.data.TimeConversions.TimestampMillisConversion(),
      new org.apache.avro.data.TimeConversions.TimestampMillisConversion(),
      null
  };

  @Override
  public org.apache.avro.Conversion<?> getConversion(int field) {
    return conversions[field];
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = (java.lang.Long)value$; break;
    case 1: code = (java.lang.CharSequence)value$; break;
    case 2: status = (java.lang.CharSequence)value$; break;
    case 3: categoryCode = (java.lang.CharSequence)value$; break;
    case 4: productName = (java.lang.CharSequence)value$; break;
    case 5: processCode = (java.lang.CharSequence)value$; break;
    case 6: processType = (java.lang.CharSequence)value$; break;
    case 7: size = (java.lang.Long)value$; break;
    case 8: controlsOutcomePec = (java.lang.CharSequence)value$; break;
    case 9: signatureTypePec = (java.lang.CharSequence)value$; break;
    case 10: certificateAuthorityPec = (java.lang.CharSequence)value$; break;
    case 11: signaturePointTimestampPec = (java.lang.CharSequence)value$; break;
    case 12: accessibility = (java.lang.CharSequence)value$; break;
    case 13: archiveLink = (java.lang.CharSequence)value$; break;
    case 14: numberOfPages = (java.lang.Long)value$; break;
    case 15: accountNumber = (java.lang.CharSequence)value$; break;
    case 16: documentDescription = (java.lang.CharSequence)value$; break;
    case 17: signatureType = (java.lang.CharSequence)value$; break;
    case 18: digitalization = (java.lang.CharSequence)value$; break;
    case 19: datamatrix = (java.lang.CharSequence)value$; break;
    case 20: creationDate = (java.time.Instant)value$; break;
    case 21: endDate = (java.time.Instant)value$; break;
    case 22: signatureDate = (java.time.Instant)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'id' field.
   * @return The value of the 'id' field.
   */
  public long getId() {
    return id;
  }


  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(long value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'code' field.
   * @return The value of the 'code' field.
   */
  public java.lang.CharSequence getCode() {
    return code;
  }


  /**
   * Sets the value of the 'code' field.
   * @param value the value to set.
   */
  public void setCode(java.lang.CharSequence value) {
    this.code = value;
  }

  /**
   * Gets the value of the 'status' field.
   * @return The value of the 'status' field.
   */
  public java.lang.CharSequence getStatus() {
    return status;
  }


  /**
   * Sets the value of the 'status' field.
   * @param value the value to set.
   */
  public void setStatus(java.lang.CharSequence value) {
    this.status = value;
  }

  /**
   * Gets the value of the 'categoryCode' field.
   * @return The value of the 'categoryCode' field.
   */
  public java.lang.CharSequence getCategoryCode() {
    return categoryCode;
  }


  /**
   * Sets the value of the 'categoryCode' field.
   * @param value the value to set.
   */
  public void setCategoryCode(java.lang.CharSequence value) {
    this.categoryCode = value;
  }

  /**
   * Gets the value of the 'productName' field.
   * @return The value of the 'productName' field.
   */
  public java.lang.CharSequence getProductName() {
    return productName;
  }


  /**
   * Sets the value of the 'productName' field.
   * @param value the value to set.
   */
  public void setProductName(java.lang.CharSequence value) {
    this.productName = value;
  }

  /**
   * Gets the value of the 'processCode' field.
   * @return The value of the 'processCode' field.
   */
  public java.lang.CharSequence getProcessCode() {
    return processCode;
  }


  /**
   * Sets the value of the 'processCode' field.
   * @param value the value to set.
   */
  public void setProcessCode(java.lang.CharSequence value) {
    this.processCode = value;
  }

  /**
   * Gets the value of the 'processType' field.
   * @return The value of the 'processType' field.
   */
  public java.lang.CharSequence getProcessType() {
    return processType;
  }


  /**
   * Sets the value of the 'processType' field.
   * @param value the value to set.
   */
  public void setProcessType(java.lang.CharSequence value) {
    this.processType = value;
  }

  /**
   * Gets the value of the 'size' field.
   * @return The value of the 'size' field.
   */
  public java.lang.Long getSize() {
    return size;
  }


  /**
   * Sets the value of the 'size' field.
   * @param value the value to set.
   */
  public void setSize(java.lang.Long value) {
    this.size = value;
  }

  /**
   * Gets the value of the 'controlsOutcomePec' field.
   * @return The value of the 'controlsOutcomePec' field.
   */
  public java.lang.CharSequence getControlsOutcomePec() {
    return controlsOutcomePec;
  }


  /**
   * Sets the value of the 'controlsOutcomePec' field.
   * @param value the value to set.
   */
  public void setControlsOutcomePec(java.lang.CharSequence value) {
    this.controlsOutcomePec = value;
  }

  /**
   * Gets the value of the 'signatureTypePec' field.
   * @return The value of the 'signatureTypePec' field.
   */
  public java.lang.CharSequence getSignatureTypePec() {
    return signatureTypePec;
  }


  /**
   * Sets the value of the 'signatureTypePec' field.
   * @param value the value to set.
   */
  public void setSignatureTypePec(java.lang.CharSequence value) {
    this.signatureTypePec = value;
  }

  /**
   * Gets the value of the 'certificateAuthorityPec' field.
   * @return The value of the 'certificateAuthorityPec' field.
   */
  public java.lang.CharSequence getCertificateAuthorityPec() {
    return certificateAuthorityPec;
  }


  /**
   * Sets the value of the 'certificateAuthorityPec' field.
   * @param value the value to set.
   */
  public void setCertificateAuthorityPec(java.lang.CharSequence value) {
    this.certificateAuthorityPec = value;
  }

  /**
   * Gets the value of the 'signaturePointTimestampPec' field.
   * @return The value of the 'signaturePointTimestampPec' field.
   */
  public java.lang.CharSequence getSignaturePointTimestampPec() {
    return signaturePointTimestampPec;
  }


  /**
   * Sets the value of the 'signaturePointTimestampPec' field.
   * @param value the value to set.
   */
  public void setSignaturePointTimestampPec(java.lang.CharSequence value) {
    this.signaturePointTimestampPec = value;
  }

  /**
   * Gets the value of the 'accessibility' field.
   * @return The value of the 'accessibility' field.
   */
  public java.lang.CharSequence getAccessibility() {
    return accessibility;
  }


  /**
   * Sets the value of the 'accessibility' field.
   * @param value the value to set.
   */
  public void setAccessibility(java.lang.CharSequence value) {
    this.accessibility = value;
  }

  /**
   * Gets the value of the 'archiveLink' field.
   * @return The value of the 'archiveLink' field.
   */
  public java.lang.CharSequence getArchiveLink() {
    return archiveLink;
  }


  /**
   * Sets the value of the 'archiveLink' field.
   * @param value the value to set.
   */
  public void setArchiveLink(java.lang.CharSequence value) {
    this.archiveLink = value;
  }

  /**
   * Gets the value of the 'numberOfPages' field.
   * @return The value of the 'numberOfPages' field.
   */
  public java.lang.Long getNumberOfPages() {
    return numberOfPages;
  }


  /**
   * Sets the value of the 'numberOfPages' field.
   * @param value the value to set.
   */
  public void setNumberOfPages(java.lang.Long value) {
    this.numberOfPages = value;
  }

  /**
   * Gets the value of the 'accountNumber' field.
   * @return The value of the 'accountNumber' field.
   */
  public java.lang.CharSequence getAccountNumber() {
    return accountNumber;
  }


  /**
   * Sets the value of the 'accountNumber' field.
   * @param value the value to set.
   */
  public void setAccountNumber(java.lang.CharSequence value) {
    this.accountNumber = value;
  }

  /**
   * Gets the value of the 'documentDescription' field.
   * @return The value of the 'documentDescription' field.
   */
  public java.lang.CharSequence getDocumentDescription() {
    return documentDescription;
  }


  /**
   * Sets the value of the 'documentDescription' field.
   * @param value the value to set.
   */
  public void setDocumentDescription(java.lang.CharSequence value) {
    this.documentDescription = value;
  }

  /**
   * Gets the value of the 'signatureType' field.
   * @return The value of the 'signatureType' field.
   */
  public java.lang.CharSequence getSignatureType() {
    return signatureType;
  }


  /**
   * Sets the value of the 'signatureType' field.
   * @param value the value to set.
   */
  public void setSignatureType(java.lang.CharSequence value) {
    this.signatureType = value;
  }

  /**
   * Gets the value of the 'digitalization' field.
   * @return The value of the 'digitalization' field.
   */
  public java.lang.CharSequence getDigitalization() {
    return digitalization;
  }


  /**
   * Sets the value of the 'digitalization' field.
   * @param value the value to set.
   */
  public void setDigitalization(java.lang.CharSequence value) {
    this.digitalization = value;
  }

  /**
   * Gets the value of the 'datamatrix' field.
   * @return The value of the 'datamatrix' field.
   */
  public java.lang.CharSequence getDatamatrix() {
    return datamatrix;
  }


  /**
   * Sets the value of the 'datamatrix' field.
   * @param value the value to set.
   */
  public void setDatamatrix(java.lang.CharSequence value) {
    this.datamatrix = value;
  }

  /**
   * Gets the value of the 'creationDate' field.
   * @return The value of the 'creationDate' field.
   */
  public java.time.Instant getCreationDate() {
    return creationDate;
  }


  /**
   * Sets the value of the 'creationDate' field.
   * @param value the value to set.
   */
  public void setCreationDate(java.time.Instant value) {
    this.creationDate = value.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
  }

  /**
   * Gets the value of the 'endDate' field.
   * @return The value of the 'endDate' field.
   */
  public java.time.Instant getEndDate() {
    return endDate;
  }


  /**
   * Sets the value of the 'endDate' field.
   * @param value the value to set.
   */
  public void setEndDate(java.time.Instant value) {
    this.endDate = value.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
  }

  /**
   * Gets the value of the 'signatureDate' field.
   * @return The value of the 'signatureDate' field.
   */
  public java.time.Instant getSignatureDate() {
    return signatureDate;
  }


  /**
   * Sets the value of the 'signatureDate' field.
   * @param value the value to set.
   */
  public void setSignatureDate(java.time.Instant value) {
    this.signatureDate = value.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
  }

  /**
   * Creates a new Document RecordBuilder.
   * @return A new Document RecordBuilder
   */
  public static eu.unicredit.dxs.Document.Builder newBuilder() {
    return new eu.unicredit.dxs.Document.Builder();
  }

  /**
   * Creates a new Document RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Document RecordBuilder
   */
  public static eu.unicredit.dxs.Document.Builder newBuilder(eu.unicredit.dxs.Document.Builder other) {
    if (other == null) {
      return new eu.unicredit.dxs.Document.Builder();
    } else {
      return new eu.unicredit.dxs.Document.Builder(other);
    }
  }

  /**
   * Creates a new Document RecordBuilder by copying an existing Document instance.
   * @param other The existing instance to copy.
   * @return A new Document RecordBuilder
   */
  public static eu.unicredit.dxs.Document.Builder newBuilder(eu.unicredit.dxs.Document other) {
    if (other == null) {
      return new eu.unicredit.dxs.Document.Builder();
    } else {
      return new eu.unicredit.dxs.Document.Builder(other);
    }
  }

  /**
   * RecordBuilder for Document instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Document>
    implements org.apache.avro.data.RecordBuilder<Document> {

    private long id;
    private java.lang.CharSequence code;
    private java.lang.CharSequence status;
    private java.lang.CharSequence categoryCode;
    private java.lang.CharSequence productName;
    private java.lang.CharSequence processCode;
    private java.lang.CharSequence processType;
    private java.lang.Long size;
    private java.lang.CharSequence controlsOutcomePec;
    private java.lang.CharSequence signatureTypePec;
    private java.lang.CharSequence certificateAuthorityPec;
    private java.lang.CharSequence signaturePointTimestampPec;
    private java.lang.CharSequence accessibility;
    private java.lang.CharSequence archiveLink;
    private java.lang.Long numberOfPages;
    private java.lang.CharSequence accountNumber;
    private java.lang.CharSequence documentDescription;
    private java.lang.CharSequence signatureType;
    private java.lang.CharSequence digitalization;
    private java.lang.CharSequence datamatrix;
    private java.time.Instant creationDate;
    private java.time.Instant endDate;
    private java.time.Instant signatureDate;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(eu.unicredit.dxs.Document.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.code)) {
        this.code = data().deepCopy(fields()[1].schema(), other.code);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.status)) {
        this.status = data().deepCopy(fields()[2].schema(), other.status);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.categoryCode)) {
        this.categoryCode = data().deepCopy(fields()[3].schema(), other.categoryCode);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.productName)) {
        this.productName = data().deepCopy(fields()[4].schema(), other.productName);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.processCode)) {
        this.processCode = data().deepCopy(fields()[5].schema(), other.processCode);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
      if (isValidValue(fields()[6], other.processType)) {
        this.processType = data().deepCopy(fields()[6].schema(), other.processType);
        fieldSetFlags()[6] = other.fieldSetFlags()[6];
      }
      if (isValidValue(fields()[7], other.size)) {
        this.size = data().deepCopy(fields()[7].schema(), other.size);
        fieldSetFlags()[7] = other.fieldSetFlags()[7];
      }
      if (isValidValue(fields()[8], other.controlsOutcomePec)) {
        this.controlsOutcomePec = data().deepCopy(fields()[8].schema(), other.controlsOutcomePec);
        fieldSetFlags()[8] = other.fieldSetFlags()[8];
      }
      if (isValidValue(fields()[9], other.signatureTypePec)) {
        this.signatureTypePec = data().deepCopy(fields()[9].schema(), other.signatureTypePec);
        fieldSetFlags()[9] = other.fieldSetFlags()[9];
      }
      if (isValidValue(fields()[10], other.certificateAuthorityPec)) {
        this.certificateAuthorityPec = data().deepCopy(fields()[10].schema(), other.certificateAuthorityPec);
        fieldSetFlags()[10] = other.fieldSetFlags()[10];
      }
      if (isValidValue(fields()[11], other.signaturePointTimestampPec)) {
        this.signaturePointTimestampPec = data().deepCopy(fields()[11].schema(), other.signaturePointTimestampPec);
        fieldSetFlags()[11] = other.fieldSetFlags()[11];
      }
      if (isValidValue(fields()[12], other.accessibility)) {
        this.accessibility = data().deepCopy(fields()[12].schema(), other.accessibility);
        fieldSetFlags()[12] = other.fieldSetFlags()[12];
      }
      if (isValidValue(fields()[13], other.archiveLink)) {
        this.archiveLink = data().deepCopy(fields()[13].schema(), other.archiveLink);
        fieldSetFlags()[13] = other.fieldSetFlags()[13];
      }
      if (isValidValue(fields()[14], other.numberOfPages)) {
        this.numberOfPages = data().deepCopy(fields()[14].schema(), other.numberOfPages);
        fieldSetFlags()[14] = other.fieldSetFlags()[14];
      }
      if (isValidValue(fields()[15], other.accountNumber)) {
        this.accountNumber = data().deepCopy(fields()[15].schema(), other.accountNumber);
        fieldSetFlags()[15] = other.fieldSetFlags()[15];
      }
      if (isValidValue(fields()[16], other.documentDescription)) {
        this.documentDescription = data().deepCopy(fields()[16].schema(), other.documentDescription);
        fieldSetFlags()[16] = other.fieldSetFlags()[16];
      }
      if (isValidValue(fields()[17], other.signatureType)) {
        this.signatureType = data().deepCopy(fields()[17].schema(), other.signatureType);
        fieldSetFlags()[17] = other.fieldSetFlags()[17];
      }
      if (isValidValue(fields()[18], other.digitalization)) {
        this.digitalization = data().deepCopy(fields()[18].schema(), other.digitalization);
        fieldSetFlags()[18] = other.fieldSetFlags()[18];
      }
      if (isValidValue(fields()[19], other.datamatrix)) {
        this.datamatrix = data().deepCopy(fields()[19].schema(), other.datamatrix);
        fieldSetFlags()[19] = other.fieldSetFlags()[19];
      }
      if (isValidValue(fields()[20], other.creationDate)) {
        this.creationDate = data().deepCopy(fields()[20].schema(), other.creationDate);
        fieldSetFlags()[20] = other.fieldSetFlags()[20];
      }
      if (isValidValue(fields()[21], other.endDate)) {
        this.endDate = data().deepCopy(fields()[21].schema(), other.endDate);
        fieldSetFlags()[21] = other.fieldSetFlags()[21];
      }
      if (isValidValue(fields()[22], other.signatureDate)) {
        this.signatureDate = data().deepCopy(fields()[22].schema(), other.signatureDate);
        fieldSetFlags()[22] = other.fieldSetFlags()[22];
      }
    }

    /**
     * Creates a Builder by copying an existing Document instance
     * @param other The existing instance to copy.
     */
    private Builder(eu.unicredit.dxs.Document other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.code)) {
        this.code = data().deepCopy(fields()[1].schema(), other.code);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.status)) {
        this.status = data().deepCopy(fields()[2].schema(), other.status);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.categoryCode)) {
        this.categoryCode = data().deepCopy(fields()[3].schema(), other.categoryCode);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.productName)) {
        this.productName = data().deepCopy(fields()[4].schema(), other.productName);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.processCode)) {
        this.processCode = data().deepCopy(fields()[5].schema(), other.processCode);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.processType)) {
        this.processType = data().deepCopy(fields()[6].schema(), other.processType);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.size)) {
        this.size = data().deepCopy(fields()[7].schema(), other.size);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.controlsOutcomePec)) {
        this.controlsOutcomePec = data().deepCopy(fields()[8].schema(), other.controlsOutcomePec);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.signatureTypePec)) {
        this.signatureTypePec = data().deepCopy(fields()[9].schema(), other.signatureTypePec);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.certificateAuthorityPec)) {
        this.certificateAuthorityPec = data().deepCopy(fields()[10].schema(), other.certificateAuthorityPec);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.signaturePointTimestampPec)) {
        this.signaturePointTimestampPec = data().deepCopy(fields()[11].schema(), other.signaturePointTimestampPec);
        fieldSetFlags()[11] = true;
      }
      if (isValidValue(fields()[12], other.accessibility)) {
        this.accessibility = data().deepCopy(fields()[12].schema(), other.accessibility);
        fieldSetFlags()[12] = true;
      }
      if (isValidValue(fields()[13], other.archiveLink)) {
        this.archiveLink = data().deepCopy(fields()[13].schema(), other.archiveLink);
        fieldSetFlags()[13] = true;
      }
      if (isValidValue(fields()[14], other.numberOfPages)) {
        this.numberOfPages = data().deepCopy(fields()[14].schema(), other.numberOfPages);
        fieldSetFlags()[14] = true;
      }
      if (isValidValue(fields()[15], other.accountNumber)) {
        this.accountNumber = data().deepCopy(fields()[15].schema(), other.accountNumber);
        fieldSetFlags()[15] = true;
      }
      if (isValidValue(fields()[16], other.documentDescription)) {
        this.documentDescription = data().deepCopy(fields()[16].schema(), other.documentDescription);
        fieldSetFlags()[16] = true;
      }
      if (isValidValue(fields()[17], other.signatureType)) {
        this.signatureType = data().deepCopy(fields()[17].schema(), other.signatureType);
        fieldSetFlags()[17] = true;
      }
      if (isValidValue(fields()[18], other.digitalization)) {
        this.digitalization = data().deepCopy(fields()[18].schema(), other.digitalization);
        fieldSetFlags()[18] = true;
      }
      if (isValidValue(fields()[19], other.datamatrix)) {
        this.datamatrix = data().deepCopy(fields()[19].schema(), other.datamatrix);
        fieldSetFlags()[19] = true;
      }
      if (isValidValue(fields()[20], other.creationDate)) {
        this.creationDate = data().deepCopy(fields()[20].schema(), other.creationDate);
        fieldSetFlags()[20] = true;
      }
      if (isValidValue(fields()[21], other.endDate)) {
        this.endDate = data().deepCopy(fields()[21].schema(), other.endDate);
        fieldSetFlags()[21] = true;
      }
      if (isValidValue(fields()[22], other.signatureDate)) {
        this.signatureDate = data().deepCopy(fields()[22].schema(), other.signatureDate);
        fieldSetFlags()[22] = true;
      }
    }

    /**
      * Gets the value of the 'id' field.
      * @return The value.
      */
    public long getId() {
      return id;
    }


    /**
      * Sets the value of the 'id' field.
      * @param value The value of 'id'.
      * @return This builder.
      */
    public eu.unicredit.dxs.Document.Builder setId(long value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'id' field has been set.
      * @return True if the 'id' field has been set, false otherwise.
      */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'id' field.
      * @return This builder.
      */
    public eu.unicredit.dxs.Document.Builder clearId() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'code' field.
      * @return The value.
      */
    public java.lang.CharSequence getCode() {
      return code;
    }


    /**
      * Sets the value of the 'code' field.
      * @param value The value of 'code'.
      * @return This builder.
      */
    public eu.unicredit.dxs.Document.Builder setCode(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.code = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'code' field has been set.
      * @return True if the 'code' field has been set, false otherwise.
      */
    public boolean hasCode() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'code' field.
      * @return This builder.
      */
    public eu.unicredit.dxs.Document.Builder clearCode() {
      code = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'status' field.
      * @return The value.
      */
    public java.lang.CharSequence getStatus() {
      return status;
    }


    /**
      * Sets the value of the 'status' field.
      * @param value The value of 'status'.
      * @return This builder.
      */
    public eu.unicredit.dxs.Document.Builder setStatus(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.status = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'status' field has been set.
      * @return True if the 'status' field has been set, false otherwise.
      */
    public boolean hasStatus() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'status' field.
      * @return This builder.
      */
    public eu.unicredit.dxs.Document.Builder clearStatus() {
      status = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'categoryCode' field.
      * @return The value.
      */
    public java.lang.CharSequence getCategoryCode() {
      return categoryCode;
    }


    /**
      * Sets the value of the 'categoryCode' field.
      * @param value The value of 'categoryCode'.
      * @return This builder.
      */
    public eu.unicredit.dxs.Document.Builder setCategoryCode(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.categoryCode = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'categoryCode' field has been set.
      * @return True if the 'categoryCode' field has been set, false otherwise.
      */
    public boolean hasCategoryCode() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'categoryCode' field.
      * @return This builder.
      */
    public eu.unicredit.dxs.Document.Builder clearCategoryCode() {
      categoryCode = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'productName' field.
      * @return The value.
      */
    public java.lang.CharSequence getProductName() {
      return productName;
    }


    /**
      * Sets the value of the 'productName' field.
      * @param value The value of 'productName'.
      * @return This builder.
      */
    public eu.unicredit.dxs.Document.Builder setProductName(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.productName = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'productName' field has been set.
      * @return True if the 'productName' field has been set, false otherwise.
      */
    public boolean hasProductName() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'productName' field.
      * @return This builder.
      */
    public eu.unicredit.dxs.Document.Builder clearProductName() {
      productName = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'processCode' field.
      * @return The value.
      */
    public java.lang.CharSequence getProcessCode() {
      return processCode;
    }


    /**
      * Sets the value of the 'processCode' field.
      * @param value The value of 'processCode'.
      * @return This builder.
      */
    public eu.unicredit.dxs.Document.Builder setProcessCode(java.lang.CharSequence value) {
      validate(fields()[5], value);
      this.processCode = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'processCode' field has been set.
      * @return True if the 'processCode' field has been set, false otherwise.
      */
    public boolean hasProcessCode() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'processCode' field.
      * @return This builder.
      */
    public eu.unicredit.dxs.Document.Builder clearProcessCode() {
      processCode = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'processType' field.
      * @return The value.
      */
    public java.lang.CharSequence getProcessType() {
      return processType;
    }


    /**
      * Sets the value of the 'processType' field.
      * @param value The value of 'processType'.
      * @return This builder.
      */
    public eu.unicredit.dxs.Document.Builder setProcessType(java.lang.CharSequence value) {
      validate(fields()[6], value);
      this.processType = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'processType' field has been set.
      * @return True if the 'processType' field has been set, false otherwise.
      */
    public boolean hasProcessType() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'processType' field.
      * @return This builder.
      */
    public eu.unicredit.dxs.Document.Builder clearProcessType() {
      processType = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'size' field.
      * @return The value.
      */
    public java.lang.Long getSize() {
      return size;
    }


    /**
      * Sets the value of the 'size' field.
      * @param value The value of 'size'.
      * @return This builder.
      */
    public eu.unicredit.dxs.Document.Builder setSize(java.lang.Long value) {
      validate(fields()[7], value);
      this.size = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
      * Checks whether the 'size' field has been set.
      * @return True if the 'size' field has been set, false otherwise.
      */
    public boolean hasSize() {
      return fieldSetFlags()[7];
    }


    /**
      * Clears the value of the 'size' field.
      * @return This builder.
      */
    public eu.unicredit.dxs.Document.Builder clearSize() {
      size = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    /**
      * Gets the value of the 'controlsOutcomePec' field.
      * @return The value.
      */
    public java.lang.CharSequence getControlsOutcomePec() {
      return controlsOutcomePec;
    }


    /**
      * Sets the value of the 'controlsOutcomePec' field.
      * @param value The value of 'controlsOutcomePec'.
      * @return This builder.
      */
    public eu.unicredit.dxs.Document.Builder setControlsOutcomePec(java.lang.CharSequence value) {
      validate(fields()[8], value);
      this.controlsOutcomePec = value;
      fieldSetFlags()[8] = true;
      return this;
    }

    /**
      * Checks whether the 'controlsOutcomePec' field has been set.
      * @return True if the 'controlsOutcomePec' field has been set, false otherwise.
      */
    public boolean hasControlsOutcomePec() {
      return fieldSetFlags()[8];
    }


    /**
      * Clears the value of the 'controlsOutcomePec' field.
      * @return This builder.
      */
    public eu.unicredit.dxs.Document.Builder clearControlsOutcomePec() {
      controlsOutcomePec = null;
      fieldSetFlags()[8] = false;
      return this;
    }

    /**
      * Gets the value of the 'signatureTypePec' field.
      * @return The value.
      */
    public java.lang.CharSequence getSignatureTypePec() {
      return signatureTypePec;
    }


    /**
      * Sets the value of the 'signatureTypePec' field.
      * @param value The value of 'signatureTypePec'.
      * @return This builder.
      */
    public eu.unicredit.dxs.Document.Builder setSignatureTypePec(java.lang.CharSequence value) {
      validate(fields()[9], value);
      this.signatureTypePec = value;
      fieldSetFlags()[9] = true;
      return this;
    }

    /**
      * Checks whether the 'signatureTypePec' field has been set.
      * @return True if the 'signatureTypePec' field has been set, false otherwise.
      */
    public boolean hasSignatureTypePec() {
      return fieldSetFlags()[9];
    }


    /**
      * Clears the value of the 'signatureTypePec' field.
      * @return This builder.
      */
    public eu.unicredit.dxs.Document.Builder clearSignatureTypePec() {
      signatureTypePec = null;
      fieldSetFlags()[9] = false;
      return this;
    }

    /**
      * Gets the value of the 'certificateAuthorityPec' field.
      * @return The value.
      */
    public java.lang.CharSequence getCertificateAuthorityPec() {
      return certificateAuthorityPec;
    }


    /**
      * Sets the value of the 'certificateAuthorityPec' field.
      * @param value The value of 'certificateAuthorityPec'.
      * @return This builder.
      */
    public eu.unicredit.dxs.Document.Builder setCertificateAuthorityPec(java.lang.CharSequence value) {
      validate(fields()[10], value);
      this.certificateAuthorityPec = value;
      fieldSetFlags()[10] = true;
      return this;
    }

    /**
      * Checks whether the 'certificateAuthorityPec' field has been set.
      * @return True if the 'certificateAuthorityPec' field has been set, false otherwise.
      */
    public boolean hasCertificateAuthorityPec() {
      return fieldSetFlags()[10];
    }


    /**
      * Clears the value of the 'certificateAuthorityPec' field.
      * @return This builder.
      */
    public eu.unicredit.dxs.Document.Builder clearCertificateAuthorityPec() {
      certificateAuthorityPec = null;
      fieldSetFlags()[10] = false;
      return this;
    }

    /**
      * Gets the value of the 'signaturePointTimestampPec' field.
      * @return The value.
      */
    public java.lang.CharSequence getSignaturePointTimestampPec() {
      return signaturePointTimestampPec;
    }


    /**
      * Sets the value of the 'signaturePointTimestampPec' field.
      * @param value The value of 'signaturePointTimestampPec'.
      * @return This builder.
      */
    public eu.unicredit.dxs.Document.Builder setSignaturePointTimestampPec(java.lang.CharSequence value) {
      validate(fields()[11], value);
      this.signaturePointTimestampPec = value;
      fieldSetFlags()[11] = true;
      return this;
    }

    /**
      * Checks whether the 'signaturePointTimestampPec' field has been set.
      * @return True if the 'signaturePointTimestampPec' field has been set, false otherwise.
      */
    public boolean hasSignaturePointTimestampPec() {
      return fieldSetFlags()[11];
    }


    /**
      * Clears the value of the 'signaturePointTimestampPec' field.
      * @return This builder.
      */
    public eu.unicredit.dxs.Document.Builder clearSignaturePointTimestampPec() {
      signaturePointTimestampPec = null;
      fieldSetFlags()[11] = false;
      return this;
    }

    /**
      * Gets the value of the 'accessibility' field.
      * @return The value.
      */
    public java.lang.CharSequence getAccessibility() {
      return accessibility;
    }


    /**
      * Sets the value of the 'accessibility' field.
      * @param value The value of 'accessibility'.
      * @return This builder.
      */
    public eu.unicredit.dxs.Document.Builder setAccessibility(java.lang.CharSequence value) {
      validate(fields()[12], value);
      this.accessibility = value;
      fieldSetFlags()[12] = true;
      return this;
    }

    /**
      * Checks whether the 'accessibility' field has been set.
      * @return True if the 'accessibility' field has been set, false otherwise.
      */
    public boolean hasAccessibility() {
      return fieldSetFlags()[12];
    }


    /**
      * Clears the value of the 'accessibility' field.
      * @return This builder.
      */
    public eu.unicredit.dxs.Document.Builder clearAccessibility() {
      accessibility = null;
      fieldSetFlags()[12] = false;
      return this;
    }

    /**
      * Gets the value of the 'archiveLink' field.
      * @return The value.
      */
    public java.lang.CharSequence getArchiveLink() {
      return archiveLink;
    }


    /**
      * Sets the value of the 'archiveLink' field.
      * @param value The value of 'archiveLink'.
      * @return This builder.
      */
    public eu.unicredit.dxs.Document.Builder setArchiveLink(java.lang.CharSequence value) {
      validate(fields()[13], value);
      this.archiveLink = value;
      fieldSetFlags()[13] = true;
      return this;
    }

    /**
      * Checks whether the 'archiveLink' field has been set.
      * @return True if the 'archiveLink' field has been set, false otherwise.
      */
    public boolean hasArchiveLink() {
      return fieldSetFlags()[13];
    }


    /**
      * Clears the value of the 'archiveLink' field.
      * @return This builder.
      */
    public eu.unicredit.dxs.Document.Builder clearArchiveLink() {
      archiveLink = null;
      fieldSetFlags()[13] = false;
      return this;
    }

    /**
      * Gets the value of the 'numberOfPages' field.
      * @return The value.
      */
    public java.lang.Long getNumberOfPages() {
      return numberOfPages;
    }


    /**
      * Sets the value of the 'numberOfPages' field.
      * @param value The value of 'numberOfPages'.
      * @return This builder.
      */
    public eu.unicredit.dxs.Document.Builder setNumberOfPages(java.lang.Long value) {
      validate(fields()[14], value);
      this.numberOfPages = value;
      fieldSetFlags()[14] = true;
      return this;
    }

    /**
      * Checks whether the 'numberOfPages' field has been set.
      * @return True if the 'numberOfPages' field has been set, false otherwise.
      */
    public boolean hasNumberOfPages() {
      return fieldSetFlags()[14];
    }


    /**
      * Clears the value of the 'numberOfPages' field.
      * @return This builder.
      */
    public eu.unicredit.dxs.Document.Builder clearNumberOfPages() {
      numberOfPages = null;
      fieldSetFlags()[14] = false;
      return this;
    }

    /**
      * Gets the value of the 'accountNumber' field.
      * @return The value.
      */
    public java.lang.CharSequence getAccountNumber() {
      return accountNumber;
    }


    /**
      * Sets the value of the 'accountNumber' field.
      * @param value The value of 'accountNumber'.
      * @return This builder.
      */
    public eu.unicredit.dxs.Document.Builder setAccountNumber(java.lang.CharSequence value) {
      validate(fields()[15], value);
      this.accountNumber = value;
      fieldSetFlags()[15] = true;
      return this;
    }

    /**
      * Checks whether the 'accountNumber' field has been set.
      * @return True if the 'accountNumber' field has been set, false otherwise.
      */
    public boolean hasAccountNumber() {
      return fieldSetFlags()[15];
    }


    /**
      * Clears the value of the 'accountNumber' field.
      * @return This builder.
      */
    public eu.unicredit.dxs.Document.Builder clearAccountNumber() {
      accountNumber = null;
      fieldSetFlags()[15] = false;
      return this;
    }

    /**
      * Gets the value of the 'documentDescription' field.
      * @return The value.
      */
    public java.lang.CharSequence getDocumentDescription() {
      return documentDescription;
    }


    /**
      * Sets the value of the 'documentDescription' field.
      * @param value The value of 'documentDescription'.
      * @return This builder.
      */
    public eu.unicredit.dxs.Document.Builder setDocumentDescription(java.lang.CharSequence value) {
      validate(fields()[16], value);
      this.documentDescription = value;
      fieldSetFlags()[16] = true;
      return this;
    }

    /**
      * Checks whether the 'documentDescription' field has been set.
      * @return True if the 'documentDescription' field has been set, false otherwise.
      */
    public boolean hasDocumentDescription() {
      return fieldSetFlags()[16];
    }


    /**
      * Clears the value of the 'documentDescription' field.
      * @return This builder.
      */
    public eu.unicredit.dxs.Document.Builder clearDocumentDescription() {
      documentDescription = null;
      fieldSetFlags()[16] = false;
      return this;
    }

    /**
      * Gets the value of the 'signatureType' field.
      * @return The value.
      */
    public java.lang.CharSequence getSignatureType() {
      return signatureType;
    }


    /**
      * Sets the value of the 'signatureType' field.
      * @param value The value of 'signatureType'.
      * @return This builder.
      */
    public eu.unicredit.dxs.Document.Builder setSignatureType(java.lang.CharSequence value) {
      validate(fields()[17], value);
      this.signatureType = value;
      fieldSetFlags()[17] = true;
      return this;
    }

    /**
      * Checks whether the 'signatureType' field has been set.
      * @return True if the 'signatureType' field has been set, false otherwise.
      */
    public boolean hasSignatureType() {
      return fieldSetFlags()[17];
    }


    /**
      * Clears the value of the 'signatureType' field.
      * @return This builder.
      */
    public eu.unicredit.dxs.Document.Builder clearSignatureType() {
      signatureType = null;
      fieldSetFlags()[17] = false;
      return this;
    }

    /**
      * Gets the value of the 'digitalization' field.
      * @return The value.
      */
    public java.lang.CharSequence getDigitalization() {
      return digitalization;
    }


    /**
      * Sets the value of the 'digitalization' field.
      * @param value The value of 'digitalization'.
      * @return This builder.
      */
    public eu.unicredit.dxs.Document.Builder setDigitalization(java.lang.CharSequence value) {
      validate(fields()[18], value);
      this.digitalization = value;
      fieldSetFlags()[18] = true;
      return this;
    }

    /**
      * Checks whether the 'digitalization' field has been set.
      * @return True if the 'digitalization' field has been set, false otherwise.
      */
    public boolean hasDigitalization() {
      return fieldSetFlags()[18];
    }


    /**
      * Clears the value of the 'digitalization' field.
      * @return This builder.
      */
    public eu.unicredit.dxs.Document.Builder clearDigitalization() {
      digitalization = null;
      fieldSetFlags()[18] = false;
      return this;
    }

    /**
      * Gets the value of the 'datamatrix' field.
      * @return The value.
      */
    public java.lang.CharSequence getDatamatrix() {
      return datamatrix;
    }


    /**
      * Sets the value of the 'datamatrix' field.
      * @param value The value of 'datamatrix'.
      * @return This builder.
      */
    public eu.unicredit.dxs.Document.Builder setDatamatrix(java.lang.CharSequence value) {
      validate(fields()[19], value);
      this.datamatrix = value;
      fieldSetFlags()[19] = true;
      return this;
    }

    /**
      * Checks whether the 'datamatrix' field has been set.
      * @return True if the 'datamatrix' field has been set, false otherwise.
      */
    public boolean hasDatamatrix() {
      return fieldSetFlags()[19];
    }


    /**
      * Clears the value of the 'datamatrix' field.
      * @return This builder.
      */
    public eu.unicredit.dxs.Document.Builder clearDatamatrix() {
      datamatrix = null;
      fieldSetFlags()[19] = false;
      return this;
    }

    /**
      * Gets the value of the 'creationDate' field.
      * @return The value.
      */
    public java.time.Instant getCreationDate() {
      return creationDate;
    }


    /**
      * Sets the value of the 'creationDate' field.
      * @param value The value of 'creationDate'.
      * @return This builder.
      */
    public eu.unicredit.dxs.Document.Builder setCreationDate(java.time.Instant value) {
      validate(fields()[20], value);
      this.creationDate = value.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
      fieldSetFlags()[20] = true;
      return this;
    }

    /**
      * Checks whether the 'creationDate' field has been set.
      * @return True if the 'creationDate' field has been set, false otherwise.
      */
    public boolean hasCreationDate() {
      return fieldSetFlags()[20];
    }


    /**
      * Clears the value of the 'creationDate' field.
      * @return This builder.
      */
    public eu.unicredit.dxs.Document.Builder clearCreationDate() {
      fieldSetFlags()[20] = false;
      return this;
    }

    /**
      * Gets the value of the 'endDate' field.
      * @return The value.
      */
    public java.time.Instant getEndDate() {
      return endDate;
    }


    /**
      * Sets the value of the 'endDate' field.
      * @param value The value of 'endDate'.
      * @return This builder.
      */
    public eu.unicredit.dxs.Document.Builder setEndDate(java.time.Instant value) {
      validate(fields()[21], value);
      this.endDate = value.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
      fieldSetFlags()[21] = true;
      return this;
    }

    /**
      * Checks whether the 'endDate' field has been set.
      * @return True if the 'endDate' field has been set, false otherwise.
      */
    public boolean hasEndDate() {
      return fieldSetFlags()[21];
    }


    /**
      * Clears the value of the 'endDate' field.
      * @return This builder.
      */
    public eu.unicredit.dxs.Document.Builder clearEndDate() {
      fieldSetFlags()[21] = false;
      return this;
    }

    /**
      * Gets the value of the 'signatureDate' field.
      * @return The value.
      */
    public java.time.Instant getSignatureDate() {
      return signatureDate;
    }


    /**
      * Sets the value of the 'signatureDate' field.
      * @param value The value of 'signatureDate'.
      * @return This builder.
      */
    public eu.unicredit.dxs.Document.Builder setSignatureDate(java.time.Instant value) {
      validate(fields()[22], value);
      this.signatureDate = value.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
      fieldSetFlags()[22] = true;
      return this;
    }

    /**
      * Checks whether the 'signatureDate' field has been set.
      * @return True if the 'signatureDate' field has been set, false otherwise.
      */
    public boolean hasSignatureDate() {
      return fieldSetFlags()[22];
    }


    /**
      * Clears the value of the 'signatureDate' field.
      * @return This builder.
      */
    public eu.unicredit.dxs.Document.Builder clearSignatureDate() {
      fieldSetFlags()[22] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Document build() {
      try {
        Document record = new Document();
        record.id = fieldSetFlags()[0] ? this.id : (java.lang.Long) defaultValue(fields()[0]);
        record.code = fieldSetFlags()[1] ? this.code : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.status = fieldSetFlags()[2] ? this.status : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.categoryCode = fieldSetFlags()[3] ? this.categoryCode : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.productName = fieldSetFlags()[4] ? this.productName : (java.lang.CharSequence) defaultValue(fields()[4]);
        record.processCode = fieldSetFlags()[5] ? this.processCode : (java.lang.CharSequence) defaultValue(fields()[5]);
        record.processType = fieldSetFlags()[6] ? this.processType : (java.lang.CharSequence) defaultValue(fields()[6]);
        record.size = fieldSetFlags()[7] ? this.size : (java.lang.Long) defaultValue(fields()[7]);
        record.controlsOutcomePec = fieldSetFlags()[8] ? this.controlsOutcomePec : (java.lang.CharSequence) defaultValue(fields()[8]);
        record.signatureTypePec = fieldSetFlags()[9] ? this.signatureTypePec : (java.lang.CharSequence) defaultValue(fields()[9]);
        record.certificateAuthorityPec = fieldSetFlags()[10] ? this.certificateAuthorityPec : (java.lang.CharSequence) defaultValue(fields()[10]);
        record.signaturePointTimestampPec = fieldSetFlags()[11] ? this.signaturePointTimestampPec : (java.lang.CharSequence) defaultValue(fields()[11]);
        record.accessibility = fieldSetFlags()[12] ? this.accessibility : (java.lang.CharSequence) defaultValue(fields()[12]);
        record.archiveLink = fieldSetFlags()[13] ? this.archiveLink : (java.lang.CharSequence) defaultValue(fields()[13]);
        record.numberOfPages = fieldSetFlags()[14] ? this.numberOfPages : (java.lang.Long) defaultValue(fields()[14]);
        record.accountNumber = fieldSetFlags()[15] ? this.accountNumber : (java.lang.CharSequence) defaultValue(fields()[15]);
        record.documentDescription = fieldSetFlags()[16] ? this.documentDescription : (java.lang.CharSequence) defaultValue(fields()[16]);
        record.signatureType = fieldSetFlags()[17] ? this.signatureType : (java.lang.CharSequence) defaultValue(fields()[17]);
        record.digitalization = fieldSetFlags()[18] ? this.digitalization : (java.lang.CharSequence) defaultValue(fields()[18]);
        record.datamatrix = fieldSetFlags()[19] ? this.datamatrix : (java.lang.CharSequence) defaultValue(fields()[19]);
        record.creationDate = fieldSetFlags()[20] ? this.creationDate : (java.time.Instant) defaultValue(fields()[20]);
        record.endDate = fieldSetFlags()[21] ? this.endDate : (java.time.Instant) defaultValue(fields()[21]);
        record.signatureDate = fieldSetFlags()[22] ? this.signatureDate : (java.time.Instant) defaultValue(fields()[22]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Document>
    WRITER$ = (org.apache.avro.io.DatumWriter<Document>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Document>
    READER$ = (org.apache.avro.io.DatumReader<Document>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}










