/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package eu.unicredit.dxs;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class Signer extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 1166012673822721156L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Signer\",\"namespace\":\"eu.unicredit.dxs\",\"fields\":[{\"name\":\"ndg\",\"type\":\"string\"},{\"name\":\"mfaMethod\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"authenticationId\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"signerReb\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"signatureChannel\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"signatureDate\",\"type\":{\"type\":\"long\",\"logicalType\":\"timestamp-millis\"}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();
  static {
    MODEL$.addLogicalTypeConversion(new org.apache.avro.data.TimeConversions.TimestampMillisConversion());
  }

  private static final BinaryMessageEncoder<Signer> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Signer> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<Signer> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<Signer> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<Signer> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this Signer to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a Signer from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a Signer instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static Signer fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.CharSequence ndg;
  private java.lang.CharSequence mfaMethod;
  private java.lang.CharSequence authenticationId;
  private java.lang.CharSequence signerReb;
  private java.lang.CharSequence signatureChannel;
  private java.time.Instant signatureDate;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Signer() {}

  /**
   * All-args constructor.
   * @param ndg The new value for ndg
   * @param mfaMethod The new value for mfaMethod
   * @param authenticationId The new value for authenticationId
   * @param signerReb The new value for signerReb
   * @param signatureChannel The new value for signatureChannel
   * @param signatureDate The new value for signatureDate
   */
  public Signer(java.lang.CharSequence ndg, java.lang.CharSequence mfaMethod, java.lang.CharSequence authenticationId, java.lang.CharSequence signerReb, java.lang.CharSequence signatureChannel, java.time.Instant signatureDate) {
    this.ndg = ndg;
    this.mfaMethod = mfaMethod;
    this.authenticationId = authenticationId;
    this.signerReb = signerReb;
    this.signatureChannel = signatureChannel;
    this.signatureDate = signatureDate.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return ndg;
    case 1: return mfaMethod;
    case 2: return authenticationId;
    case 3: return signerReb;
    case 4: return signatureChannel;
    case 5: return signatureDate;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  private static final org.apache.avro.Conversion<?>[] conversions =
      new org.apache.avro.Conversion<?>[] {
      null,
      null,
      null,
      null,
      null,
      new org.apache.avro.data.TimeConversions.TimestampMillisConversion(),
      null
  };

  @Override
  public org.apache.avro.Conversion<?> getConversion(int field) {
    return conversions[field];
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: ndg = (java.lang.CharSequence)value$; break;
    case 1: mfaMethod = (java.lang.CharSequence)value$; break;
    case 2: authenticationId = (java.lang.CharSequence)value$; break;
    case 3: signerReb = (java.lang.CharSequence)value$; break;
    case 4: signatureChannel = (java.lang.CharSequence)value$; break;
    case 5: signatureDate = (java.time.Instant)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'ndg' field.
   * @return The value of the 'ndg' field.
   */
  public java.lang.CharSequence getNdg() {
    return ndg;
  }


  /**
   * Sets the value of the 'ndg' field.
   * @param value the value to set.
   */
  public void setNdg(java.lang.CharSequence value) {
    this.ndg = value;
  }

  /**
   * Gets the value of the 'mfaMethod' field.
   * @return The value of the 'mfaMethod' field.
   */
  public java.lang.CharSequence getMfaMethod() {
    return mfaMethod;
  }


  /**
   * Sets the value of the 'mfaMethod' field.
   * @param value the value to set.
   */
  public void setMfaMethod(java.lang.CharSequence value) {
    this.mfaMethod = value;
  }

  /**
   * Gets the value of the 'authenticationId' field.
   * @return The value of the 'authenticationId' field.
   */
  public java.lang.CharSequence getAuthenticationId() {
    return authenticationId;
  }


  /**
   * Sets the value of the 'authenticationId' field.
   * @param value the value to set.
   */
  public void setAuthenticationId(java.lang.CharSequence value) {
    this.authenticationId = value;
  }

  /**
   * Gets the value of the 'signerReb' field.
   * @return The value of the 'signerReb' field.
   */
  public java.lang.CharSequence getSignerReb() {
    return signerReb;
  }


  /**
   * Sets the value of the 'signerReb' field.
   * @param value the value to set.
   */
  public void setSignerReb(java.lang.CharSequence value) {
    this.signerReb = value;
  }

  /**
   * Gets the value of the 'signatureChannel' field.
   * @return The value of the 'signatureChannel' field.
   */
  public java.lang.CharSequence getSignatureChannel() {
    return signatureChannel;
  }


  /**
   * Sets the value of the 'signatureChannel' field.
   * @param value the value to set.
   */
  public void setSignatureChannel(java.lang.CharSequence value) {
    this.signatureChannel = value;
  }

  /**
   * Gets the value of the 'signatureDate' field.
   * @return The value of the 'signatureDate' field.
   */
  public java.time.Instant getSignatureDate() {
    return signatureDate;
  }


  /**
   * Sets the value of the 'signatureDate' field.
   * @param value the value to set.
   */
  public void setSignatureDate(java.time.Instant value) {
    this.signatureDate = value.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
  }

  /**
   * Creates a new Signer RecordBuilder.
   * @return A new Signer RecordBuilder
   */
  public static eu.unicredit.dxs.Signer.Builder newBuilder() {
    return new eu.unicredit.dxs.Signer.Builder();
  }

  /**
   * Creates a new Signer RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Signer RecordBuilder
   */
  public static eu.unicredit.dxs.Signer.Builder newBuilder(eu.unicredit.dxs.Signer.Builder other) {
    if (other == null) {
      return new eu.unicredit.dxs.Signer.Builder();
    } else {
      return new eu.unicredit.dxs.Signer.Builder(other);
    }
  }

  /**
   * Creates a new Signer RecordBuilder by copying an existing Signer instance.
   * @param other The existing instance to copy.
   * @return A new Signer RecordBuilder
   */
  public static eu.unicredit.dxs.Signer.Builder newBuilder(eu.unicredit.dxs.Signer other) {
    if (other == null) {
      return new eu.unicredit.dxs.Signer.Builder();
    } else {
      return new eu.unicredit.dxs.Signer.Builder(other);
    }
  }

  /**
   * RecordBuilder for Signer instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Signer>
    implements org.apache.avro.data.RecordBuilder<Signer> {

    private java.lang.CharSequence ndg;
    private java.lang.CharSequence mfaMethod;
    private java.lang.CharSequence authenticationId;
    private java.lang.CharSequence signerReb;
    private java.lang.CharSequence signatureChannel;
    private java.time.Instant signatureDate;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(eu.unicredit.dxs.Signer.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.ndg)) {
        this.ndg = data().deepCopy(fields()[0].schema(), other.ndg);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.mfaMethod)) {
        this.mfaMethod = data().deepCopy(fields()[1].schema(), other.mfaMethod);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.authenticationId)) {
        this.authenticationId = data().deepCopy(fields()[2].schema(), other.authenticationId);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.signerReb)) {
        this.signerReb = data().deepCopy(fields()[3].schema(), other.signerReb);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.signatureChannel)) {
        this.signatureChannel = data().deepCopy(fields()[4].schema(), other.signatureChannel);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.signatureDate)) {
        this.signatureDate = data().deepCopy(fields()[5].schema(), other.signatureDate);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
    }

    /**
     * Creates a Builder by copying an existing Signer instance
     * @param other The existing instance to copy.
     */
    private Builder(eu.unicredit.dxs.Signer other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.ndg)) {
        this.ndg = data().deepCopy(fields()[0].schema(), other.ndg);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.mfaMethod)) {
        this.mfaMethod = data().deepCopy(fields()[1].schema(), other.mfaMethod);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.authenticationId)) {
        this.authenticationId = data().deepCopy(fields()[2].schema(), other.authenticationId);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.signerReb)) {
        this.signerReb = data().deepCopy(fields()[3].schema(), other.signerReb);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.signatureChannel)) {
        this.signatureChannel = data().deepCopy(fields()[4].schema(), other.signatureChannel);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.signatureDate)) {
        this.signatureDate = data().deepCopy(fields()[5].schema(), other.signatureDate);
        fieldSetFlags()[5] = true;
      }
    }

    /**
      * Gets the value of the 'ndg' field.
      * @return The value.
      */
    public java.lang.CharSequence getNdg() {
      return ndg;
    }


    /**
      * Sets the value of the 'ndg' field.
      * @param value The value of 'ndg'.
      * @return This builder.
      */
    public eu.unicredit.dxs.Signer.Builder setNdg(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.ndg = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'ndg' field has been set.
      * @return True if the 'ndg' field has been set, false otherwise.
      */
    public boolean hasNdg() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'ndg' field.
      * @return This builder.
      */
    public eu.unicredit.dxs.Signer.Builder clearNdg() {
      ndg = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'mfaMethod' field.
      * @return The value.
      */
    public java.lang.CharSequence getMfaMethod() {
      return mfaMethod;
    }


    /**
      * Sets the value of the 'mfaMethod' field.
      * @param value The value of 'mfaMethod'.
      * @return This builder.
      */
    public eu.unicredit.dxs.Signer.Builder setMfaMethod(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.mfaMethod = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'mfaMethod' field has been set.
      * @return True if the 'mfaMethod' field has been set, false otherwise.
      */
    public boolean hasMfaMethod() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'mfaMethod' field.
      * @return This builder.
      */
    public eu.unicredit.dxs.Signer.Builder clearMfaMethod() {
      mfaMethod = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'authenticationId' field.
      * @return The value.
      */
    public java.lang.CharSequence getAuthenticationId() {
      return authenticationId;
    }


    /**
      * Sets the value of the 'authenticationId' field.
      * @param value The value of 'authenticationId'.
      * @return This builder.
      */
    public eu.unicredit.dxs.Signer.Builder setAuthenticationId(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.authenticationId = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'authenticationId' field has been set.
      * @return True if the 'authenticationId' field has been set, false otherwise.
      */
    public boolean hasAuthenticationId() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'authenticationId' field.
      * @return This builder.
      */
    public eu.unicredit.dxs.Signer.Builder clearAuthenticationId() {
      authenticationId = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'signerReb' field.
      * @return The value.
      */
    public java.lang.CharSequence getSignerReb() {
      return signerReb;
    }


    /**
      * Sets the value of the 'signerReb' field.
      * @param value The value of 'signerReb'.
      * @return This builder.
      */
    public eu.unicredit.dxs.Signer.Builder setSignerReb(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.signerReb = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'signerReb' field has been set.
      * @return True if the 'signerReb' field has been set, false otherwise.
      */
    public boolean hasSignerReb() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'signerReb' field.
      * @return This builder.
      */
    public eu.unicredit.dxs.Signer.Builder clearSignerReb() {
      signerReb = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'signatureChannel' field.
      * @return The value.
      */
    public java.lang.CharSequence getSignatureChannel() {
      return signatureChannel;
    }


    /**
      * Sets the value of the 'signatureChannel' field.
      * @param value The value of 'signatureChannel'.
      * @return This builder.
      */
    public eu.unicredit.dxs.Signer.Builder setSignatureChannel(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.signatureChannel = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'signatureChannel' field has been set.
      * @return True if the 'signatureChannel' field has been set, false otherwise.
      */
    public boolean hasSignatureChannel() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'signatureChannel' field.
      * @return This builder.
      */
    public eu.unicredit.dxs.Signer.Builder clearSignatureChannel() {
      signatureChannel = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'signatureDate' field.
      * @return The value.
      */
    public java.time.Instant getSignatureDate() {
      return signatureDate;
    }


    /**
      * Sets the value of the 'signatureDate' field.
      * @param value The value of 'signatureDate'.
      * @return This builder.
      */
    public eu.unicredit.dxs.Signer.Builder setSignatureDate(java.time.Instant value) {
      validate(fields()[5], value);
      this.signatureDate = value.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'signatureDate' field has been set.
      * @return True if the 'signatureDate' field has been set, false otherwise.
      */
    public boolean hasSignatureDate() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'signatureDate' field.
      * @return This builder.
      */
    public eu.unicredit.dxs.Signer.Builder clearSignatureDate() {
      fieldSetFlags()[5] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Signer build() {
      try {
        Signer record = new Signer();
        record.ndg = fieldSetFlags()[0] ? this.ndg : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.mfaMethod = fieldSetFlags()[1] ? this.mfaMethod : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.authenticationId = fieldSetFlags()[2] ? this.authenticationId : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.signerReb = fieldSetFlags()[3] ? this.signerReb : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.signatureChannel = fieldSetFlags()[4] ? this.signatureChannel : (java.lang.CharSequence) defaultValue(fields()[4]);
        record.signatureDate = fieldSetFlags()[5] ? this.signatureDate : (java.time.Instant) defaultValue(fields()[5]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Signer>
    WRITER$ = (org.apache.avro.io.DatumWriter<Signer>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Signer>
    READER$ = (org.apache.avro.io.DatumReader<Signer>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}










